# Generated by Django 5.0.1 on 2024-01-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0003_alter_option_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='active_time',
            field=models.DurationField(help_text='Enter the active time for the poll in the format: DD HH:MM:SS.'),
        ),
    ]
