# Generated by Django 5.0.1 on 2024-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0004_alter_poll_active_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='quorum_type',
            field=models.CharField(choices=[('P', 'Percent'), ('N', 'Number')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='quorum',
            field=models.FloatField(),
        ),
    ]
