# Generated by Django 5.0.1 on 2024-01-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0005_poll_quorum_type_alter_poll_quorum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='quorum',
            field=models.IntegerField(),
        ),
    ]
