# Generated by Django 5.0.1 on 2024-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0007_poll_end_time_poll_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='start_option',
            field=models.CharField(choices=[('S', 'Start Time'), ('I', 'Immediately')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='poll',
            name='time_option',
            field=models.CharField(choices=[('A', 'Active Time'), ('E', 'End Time')], default='A', max_length=1),
        ),
    ]
