# Generated by Django 5.0.1 on 2024-01-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0008_poll_start_option_poll_time_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='active_time',
            field=models.DurationField(blank=True, help_text='Enter the active time for the poll in the format: DD HH:MM:SS.', null=True),
        ),
    ]
