# Generated by Django 5.0.1 on 2024-01-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0009_alter_poll_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='quorum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
